import type { AssessmentDefinition } from "@/lib/assessment/types";

export const PRIMARY_A2_ASSESSMENT_ID = "primary-a2-exit-pilot" as const;

export const PRIMARY_A2_ASSESSMENT_PILOT: AssessmentDefinition = {
  schemaVersion: 1,
  id: PRIMARY_A2_ASSESSMENT_ID,
  contentVersion: "2026.08-pilot.5",
  title: "Primary A2 English Check",
  level: "A2",
  audience: "Students finishing Primary",
  estimatedMinutes: 105,
  sections: [
    {
      id: "listening",
      title: "Listening",
      description: "Listen carefully. Replay a recording when you need to hear it again.",
      parts: [
        {
          id: "listening-part-1",
          partNumber: 1,
          kind: "listening_character_match",
          title: "Names and people",
          instructions: "Listen and choose the correct name for each person. There are two extra names.",
          activity: {
            audioText: "Look at the children at the school fair. The boy wearing the blue hoodie is Oliver. The girl in the light blue dress is Lucy. The boy with the blue winter hat is called Harry. The girl with two buns and a heart on her pink shirt is Daisy. The boy wearing the green sports shirt and a cap is Jack.",
            names: [
              { id: "lp1-name-oliver", name: "Oliver" },
              { id: "lp1-name-lucy", name: "Lucy" },
              { id: "lp1-name-harry", name: "Harry" },
              { id: "lp1-name-daisy", name: "Daisy" },
              { id: "lp1-name-jack", name: "Jack" },
              { id: "lp1-name-sally", name: "Sally" },
              { id: "lp1-name-tom", name: "Tom" },
            ],
            characters: [
              { id: "lp1-c1", imageSrc: "/assets/Characters Live Games/boy 1.png", imageAlt: "A boy wearing a blue hoodie", clueLabel: "A", correctNameId: "lp1-name-oliver" },
              { id: "lp1-c2", imageSrc: "/assets/Characters Live Games/girl 1.png", imageAlt: "A girl wearing a light blue dress", clueLabel: "B", correctNameId: "lp1-name-lucy" },
              { id: "lp1-c3", imageSrc: "/assets/Characters Live Games/boy 2.png", imageAlt: "A boy wearing a blue winter hat and black shirt", clueLabel: "C", correctNameId: "lp1-name-harry" },
              { id: "lp1-c4", imageSrc: "/assets/Characters Live Games/girl 2.png", imageAlt: "A girl with two buns wearing a pink heart shirt", clueLabel: "D", correctNameId: "lp1-name-daisy" },
              { id: "lp1-c5", imageSrc: "/assets/Characters Live Games/boy 3.png", imageAlt: "A boy wearing a green sports shirt and backwards cap", clueLabel: "E", correctNameId: "lp1-name-jack" },
            ],
          },
        },
        {
          id: "listening-part-2",
          partNumber: 2,
          kind: "listening_information",
          title: "The school trip",
          instructions: "Listen and write a word or number in each space.",
          activity: {
            organizerTitle: "Green Farm School Trip",
            audioText: "The class trip is on Friday the eighteenth of August. We are going to Green Farm. The bus will leave school at half past eight in the morning. Please bring a hat and a bottle of water. Lunch will be at twelve o'clock. The teacher in charge is Mrs Parker. Her surname is spelled P A R K E R. The trip costs six pounds for each student.",
            fields: [
              { id: "lp2-date", label: "Date: Friday ___ August", acceptedAnswers: ["18", "18th", "eighteenth"] },
              { id: "lp2-time", label: "Bus leaves at", acceptedAnswers: ["8:30", "8.30", "half past eight", "eight thirty"] },
              { id: "lp2-bring", label: "Bring a hat and a bottle of", acceptedAnswers: ["water"] },
              { id: "lp2-teacher", label: "Teacher: Mrs", acceptedAnswers: ["Parker"] },
              { id: "lp2-cost", label: "Cost: £", acceptedAnswers: ["6", "six"] },
            ],
          },
        },
        {
          id: "listening-part-3",
          partNumber: 3,
          kind: "listening_item_match",
          title: "Holiday activities",
          instructions: "Listen and match each person to what they did. There are two extra activities.",
          activity: {
            audioText: "The children did different things during the holiday. Mia spent Saturday painting a picture of the sea. Ethan rode his bike with his older brother. Leo stayed inside and read a comic about space. Zara sang in a concert at the town hall. Ben took photos of birds in the park.",
            choices: [
              { id: "lp3-painting", label: "painted a picture", imageSrc: "/pilots/games-flashcards/hobbies/01-painting.webp" },
              { id: "lp3-bike", label: "rode a bike", imageSrc: "/pilots/games-flashcards/hobbies/07-riding-a-bike.webp" },
              { id: "lp3-comic", label: "read a comic", imageSrc: "/pilots/games-flashcards/hobbies/09-reading-comics.webp" },
              { id: "lp3-singing", label: "sang in a concert", imageSrc: "/pilots/games-flashcards/hobbies/03-singing.webp" },
              { id: "lp3-photos", label: "took photos" },
              { id: "lp3-dancing", label: "went dancing", imageSrc: "/pilots/games-flashcards/hobbies/04-dancing.webp" },
              { id: "lp3-models", label: "built a model", imageSrc: "/pilots/games-flashcards/hobbies/08-building-models.webp" },
            ],
            prompts: [
              { id: "lp3-mia", label: "Mia", correctChoiceId: "lp3-painting" },
              { id: "lp3-ethan", label: "Ethan", correctChoiceId: "lp3-bike" },
              { id: "lp3-leo", label: "Leo", correctChoiceId: "lp3-comic" },
              { id: "lp3-zara", label: "Zara", correctChoiceId: "lp3-singing" },
              { id: "lp3-ben", label: "Ben", correctChoiceId: "lp3-photos" },
            ],
          },
        },
        {
          id: "listening-part-4",
          partNumber: 4,
          kind: "listening_picture_choice",
          title: "Choose the picture",
          instructions: "Listen to each recording and choose the correct picture.",
          activity: {
            items: [
              { id: "lp4-q1", audioText: "What did Anna do after school? Anna wanted to read, but she finished her picture for the art show instead.", correctChoiceId: "lp4-q1-drawing", choices: [
                { id: "lp4-q1-dancing", imageSrc: "/pilots/games-listen-choose/hobbies/q1-dancing.webp", imageAlt: "A child dancing", label: "A" },
                { id: "lp4-q1-drawing", imageSrc: "/pilots/games-listen-choose/hobbies/q1-drawing.webp", imageAlt: "A child drawing", label: "B" },
                { id: "lp4-q1-reading", imageSrc: "/pilots/games-listen-choose/hobbies/q1-reading.webp", imageAlt: "A child reading", label: "C" },
              ] },
              { id: "lp4-q2", audioText: "Which activity does Ethan like best? He sometimes builds robots, but riding his bike is his favourite thing to do.", correctChoiceId: "lp4-q2-bike", choices: [
                { id: "lp4-q2-robot", imageSrc: "/pilots/games-listen-choose/hobbies/q2-ethan-building-robot.webp", imageAlt: "Ethan building a robot", label: "A" },
                { id: "lp4-q2-football", imageSrc: "/pilots/games-listen-choose/hobbies/q2-ethan-playing-football.webp", imageAlt: "Ethan playing football", label: "B" },
                { id: "lp4-q2-bike", imageSrc: "/pilots/games-listen-choose/hobbies/q2-ethan-riding-bike.webp", imageAlt: "Ethan riding a bike", label: "C" },
              ] },
              { id: "lp4-q3", audioText: "What is Leo doing now? He put down his comic and picked up his guitar to practise a new song.", correctChoiceId: "lp4-q3-guitar", choices: [
                { id: "lp4-q3-guitar", imageSrc: "/pilots/games-listen-choose/hobbies/q3-leo-playing-guitar.webp", imageAlt: "Leo playing guitar", label: "A" },
                { id: "lp4-q3-comic", imageSrc: "/pilots/games-listen-choose/hobbies/q3-leo-reading-comic.webp", imageAlt: "Leo reading a comic", label: "B" },
                { id: "lp4-q3-photos", imageSrc: "/pilots/games-listen-choose/hobbies/q3-leo-taking-photos.webp", imageAlt: "Leo taking photos", label: "C" },
              ] },
              { id: "lp4-q4", audioText: "What will Zara do at the school show? She was going to paint, but now she is going to sing with her class.", correctChoiceId: "lp4-q4-singing", choices: [
                { id: "lp4-q4-dancing", imageSrc: "/pilots/games-listen-choose/hobbies/q4-zara-dancing.webp", imageAlt: "Zara dancing", label: "A" },
                { id: "lp4-q4-painting", imageSrc: "/pilots/games-listen-choose/hobbies/q4-zara-painting.webp", imageAlt: "Zara painting", label: "B" },
                { id: "lp4-q4-singing", imageSrc: "/pilots/games-listen-choose/hobbies/q4-zara-singing.webp", imageAlt: "Zara singing", label: "C" },
              ] },
              { id: "lp4-q5", audioText: "What did the two girls make together? Mia and Zara recorded a short film about their art project.", correctChoiceId: "lp4-q5-recording", choices: [
                { id: "lp4-q5-dancing", imageSrc: "/pilots/games-listen-choose/hobbies/q5-mia-reading-zara-dancing.webp", imageAlt: "Two girls reading and dancing", label: "A" },
                { id: "lp4-q5-recording", imageSrc: "/pilots/games-listen-choose/hobbies/q5-mia-zara-recording-art-project.webp", imageAlt: "Two girls recording an art project", label: "B" },
                { id: "lp4-q5-bikes", imageSrc: "/pilots/games-listen-choose/hobbies/q5-mia-zara-riding-bikes.webp", imageAlt: "Two girls riding bikes", label: "C" },
              ] },
            ],
          },
        },
        {
          id: "listening-part-5",
          partNumber: 5,
          kind: "listening_colour_picture",
          title: "Listen and colour",
          instructions: "Listen, choose a colour, and tap the correct object in the picture.",
          activity: {
            audioText: "Look at the room. Colour the window blue. Now find the table on the left and colour it yellow. Colour the cupboard green. Can you see the toy boat in the middle? Colour the boat purple. Finally, colour the round ball red.",
            image: {
              src: "/listen-color-backgrounds/scene-easy.svg",
              alt: "A line drawing of a room with a window, table, cupboard, toy boat, ball and chair",
            },
            palette: [
              { id: "blue", label: "Blue", hex: "#3b82f6" },
              { id: "yellow", label: "Yellow", hex: "#facc15" },
              { id: "green", label: "Green", hex: "#22c55e" },
              { id: "purple", label: "Purple", hex: "#a855f7" },
              { id: "red", label: "Red", hex: "#ef4444" },
            ],
            targets: [
              { id: "lp5-window", label: "Window", xPercent: 9.4, yPercent: 20, widthPercent: 19.4, heightPercent: 16.7, correctColourId: "blue" },
              { id: "lp5-table", label: "Table", xPercent: 10.6, yPercent: 42.2, widthPercent: 21.3, heightPercent: 25.6, correctColourId: "yellow" },
              { id: "lp5-cupboard", label: "Cupboard", xPercent: 35, yPercent: 33.3, widthPercent: 11.3, heightPercent: 28.9, correctColourId: "green" },
              { id: "lp5-boat", label: "Toy boat", xPercent: 40, yPercent: 62.2, widthPercent: 21.3, heightPercent: 14.5, correctColourId: "purple" },
              { id: "lp5-ball", label: "Ball", xPercent: 64.8, yPercent: 65.1, widthPercent: 8, heightPercent: 14.2, correctColourId: "red" },
            ],
          },
        },
      ],
    },
    {
      id: "reading-writing",
      title: "Reading & Writing",
      description: "Read carefully and answer every question you can.",
      parts: [
        {
          id: "rw-part-1",
          partNumber: 1,
          kind: "definition_match",
          title: "Words and definitions",
          instructions: "Choose the word that matches each definition. There are two extra words.",
          extraWords: [
            { id: "p1-extra-helmet", word: "helmet" },
            { id: "p1-extra-calendar", word: "calendar" },
          ],
          activity: {
            title: "Words and definitions",
            instructions: "Choose the word that matches each definition.",
            shuffleWords: false,
            pairs: [
              { id: "p1-bridge", word: "bridge", definition: "You use this to cross over a river or road." },
              { id: "p1-diary", word: "diary", definition: "A book where you write what happens each day." },
              { id: "p1-gloves", word: "gloves", definition: "You wear these on your hands when it is cold." },
              { id: "p1-invitation", word: "invitation", definition: "A message asking someone to come to a party or event." },
              { id: "p1-passenger", word: "passenger", definition: "A person travelling in a car, bus, train or plane." },
            ],
          },
        },
        {
          id: "rw-part-2",
          partNumber: 2,
          kind: "picture_yes_no",
          title: "Look and read",
          instructions: "Look at the picture. Choose yes if the sentence is true or no if it is false.",
          activity: {
            image: {
              src: "/listen-color-backgrounds/scene-medium.svg",
              alt: "A room with a table, a ball, a cupboard, a chair, pictures and other objects",
            },
            statements: [
              { id: "p2-q1", text: "There is a ball on the floor.", correctAnswer: "yes" },
              { id: "p2-q2", text: "The cupboard has four doors.", correctAnswer: "yes" },
              { id: "p2-q3", text: "There is a clock above the table.", correctAnswer: "no" },
              { id: "p2-q4", text: "A chair is standing near the cupboard.", correctAnswer: "yes" },
              { id: "p2-q5", text: "There are three windows on the wall.", correctAnswer: "no" },
              { id: "p2-q6", text: "A picture of a house is hanging on the right.", correctAnswer: "yes" },
            ],
          },
        },
        {
          id: "rw-part-3",
          partNumber: 3,
          kind: "dialogue_bank",
          title: "Complete the conversation",
          instructions: "Choose the best response for each gap. There are two extra responses.",
          activity: {
            opening: "Emma is talking to her friend Jack about the weekend.",
            exchanges: [
              { id: "p3-q1", speaker: "Emma", prompt: "Hi Jack! What did you do on Saturday?", correctResponseId: "p3-r4" },
              { id: "p3-q2", speaker: "Emma", prompt: "Was the new pool good?", correctResponseId: "p3-r1" },
              { id: "p3-q3", speaker: "Emma", prompt: "Who did you go with?", correctResponseId: "p3-r6" },
              { id: "p3-q4", speaker: "Emma", prompt: "How long did you stay there?", correctResponseId: "p3-r2" },
              { id: "p3-q5", speaker: "Emma", prompt: "Can I come with you next time?", correctResponseId: "p3-r7" },
            ],
            responses: [
              { id: "p3-r1", text: "Yes, it was brilliant!" },
              { id: "p3-r2", text: "For about two hours." },
              { id: "p3-r3", text: "It opens at nine o'clock." },
              { id: "p3-r4", text: "I went swimming at the new sports centre." },
              { id: "p3-r5", text: "No, I don't like basketball." },
              { id: "p3-r6", text: "My cousin came with me." },
              { id: "p3-r7", text: "Of course! Let's ask your mum." },
            ],
          },
        },
        {
          id: "rw-part-4",
          partNumber: 4,
          kind: "story_bank_title",
          title: "The missing lunchbox",
          instructions: "Choose words from the bank to complete the story. Then choose the best title.",
          activity: {
            storyTitle: "Read the story",
            words: [
              { id: "p4-w-looked", word: "looked" },
              { id: "p4-w-hungry", word: "hungry" },
              { id: "p4-w-inside", word: "inside" },
              { id: "p4-w-laughed", word: "laughed" },
              { id: "p4-w-sandwich", word: "sandwich" },
              { id: "p4-w-cloudy", word: "cloudy" },
              { id: "p4-w-carried", word: "carried" },
            ],
            segments: [
              { type: "text", id: "p4-t1", text: "At lunchtime, Ben opened his school bag, but his lunchbox was not " },
              { type: "gap", id: "p4-g1", correctWordId: "p4-w-inside" },
              { type: "text", id: "p4-t2", text: ". He was very " },
              { type: "gap", id: "p4-g2", correctWordId: "p4-w-hungry" },
              { type: "text", id: "p4-t3", text: ", so he and Mia " },
              { type: "gap", id: "p4-g3", correctWordId: "p4-w-looked" },
              { type: "text", id: "p4-t4", text: " under the desks. Then Mia saw the lunchbox beside the classroom plant. Ben opened it and found a cheese " },
              { type: "gap", id: "p4-g4", correctWordId: "p4-w-sandwich" },
              { type: "text", id: "p4-t5", text: ". The friends " },
              { type: "gap", id: "p4-g5", correctWordId: "p4-w-laughed" },
              { type: "text", id: "p4-t6", text: " and went outside to eat together." },
            ],
            titleQuestionId: "p4-title",
            titleOptions: [
              { id: "p4-title-a", text: "A surprising place for lunch" },
              { id: "p4-title-b", text: "Ben's new school bag" },
              { id: "p4-title-c", text: "Food for the classroom plant" },
            ],
            correctTitleId: "p4-title-a",
          },
        },
        {
          id: "rw-part-5",
          partNumber: 5,
          kind: "short_answer_reading",
          title: "The school garden",
          instructions: "Read the story and choose the best answer for each question.",
          activity: {
            passage: {
              title: "A surprise in the garden",
              text: "On Tuesday afternoon, Maya's class went to work in the school garden. Maya and Leo carried water while their teacher planted tomato seeds. Near the old tree, Leo found a tiny bird on the ground. It could not fly. The children put the bird in a quiet box and called the animal centre. A woman arrived twenty minutes later and took it somewhere safe. Before the class went home, their teacher thanked them for being calm and helpful.",
            },
            questions: [
              {
                id: "p5-q1",
                prompt: "When did the class work in the garden?",
                acceptedAnswers: ["Tuesday afternoon", "On Tuesday afternoon"],
              },
              {
                id: "p5-q2",
                prompt: "What were Maya and Leo carrying?",
                acceptedAnswers: ["water"],
              },
              {
                id: "p5-q3",
                prompt: "Where did Leo find the bird?",
                acceptedAnswers: ["near the old tree", "by the old tree"],
              },
              {
                id: "p5-q4",
                prompt: "Why did the children call the animal centre?",
                acceptedAnswers: ["it could not fly", "the bird could not fly", "because it could not fly"],
              },
              {
                id: "p5-q5",
                prompt: "How did the teacher feel about the children?",
                acceptedAnswers: ["pleased", "happy", "thankful"],
              },
            ],
          },
        },
        {
          id: "rw-part-6",
          partNumber: 6,
          kind: "cloze_choice",
          title: "A visit to the library",
          instructions: "Choose the best word for each gap.",
          activity: {
            title: "A visit to the library",
            instructions: "Choose the best word for each gap.",
            passageTitle: "My new library card",
            shuffleOptions: false,
            segments: [
              { type: "text", id: "p6-t1", text: "Yesterday, my sister and I " },
              { type: "gap", id: "p6-g1", options: ["go", "went", "going"], correctAnswer: "went" },
              { type: "text", id: "p6-t2", text: " to the new library. It is " },
              { type: "gap", id: "p6-g2", options: ["between", "during", "without"], correctAnswer: "between" },
              { type: "text", id: "p6-t3", text: " the park and the swimming pool. A librarian showed " },
              { type: "gap", id: "p6-g3", options: ["we", "our", "us"], correctAnswer: "us" },
              { type: "text", id: "p6-t4", text: " where to find adventure stories. I chose a book " },
              { type: "gap", id: "p6-g4", options: ["because", "but", "than"], correctAnswer: "because" },
              { type: "text", id: "p6-t5", text: " the picture on the cover looked exciting. We will " },
              { type: "gap", id: "p6-g5", options: ["return", "returned", "returns"], correctAnswer: "return" },
              { type: "text", id: "p6-t6", text: " the books next Saturday." },
            ],
          },
        },
        {
          id: "rw-part-7",
          partNumber: 7,
          kind: "cloze_open",
          title: "A message from Sam",
          instructions: "Write one word in each gap. There is no word bank.",
          activity: {
            title: "A message from Sam",
            instructions: "Write one word in each gap.",
            passageTitle: "The football match",
            caseSensitive: false,
            punctuationSensitive: false,
            segments: [
              { type: "text", id: "p7-t1", text: "Hi Alex,\n\nWould you like to come " },
              { type: "gap", id: "p7-g1", correctAnswers: ["to"] },
              { type: "text", id: "p7-t2", text: " the football match with me on Saturday? My uncle has three tickets, " },
              { type: "gap", id: "p7-g2", correctAnswers: ["so"] },
              { type: "text", id: "p7-t3", text: " you can sit with us. The match starts " },
              { type: "gap", id: "p7-g3", correctAnswers: ["at"] },
              { type: "text", id: "p7-t4", text: " two o'clock. We can meet outside your house and go there " },
              { type: "gap", id: "p7-g4", correctAnswers: ["by"] },
              { type: "text", id: "p7-t5", text: " bus. Please ask your parents and tell " },
              { type: "gap", id: "p7-g5", correctAnswers: ["me"] },
              { type: "text", id: "p7-t6", text: " tonight.\n\nSam" },
            ],
          },
        },
      ],
    },
    {
      id: "speaking",
      title: "Speaking",
      description: "Look carefully, plan what to say, and record a clear response for your teacher.",
      parts: [
        {
          id: "speaking-part-1",
          partNumber: 1,
          kind: "speaking_picture_differences",
          title: "Find the differences",
          instructions: "Look at both pictures. Record yourself explaining four differences.",
          activity: {
            responseId: "sp1-recording",
            prompt: "Say four differences. You can use: In picture A… but in picture B…",
            maxDurationSeconds: 90,
            images: [
              { src: "/listen-color-backgrounds/scene-easy.svg", alt: "Room picture A", label: "Picture A" },
              { src: "/listen-color-backgrounds/scene-medium.svg", alt: "Room picture B", label: "Picture B" },
            ],
          },
        },
        {
          id: "speaking-part-2",
          partNumber: 2,
          kind: "speaking_question_exchange",
          title: "Ask and answer questions",
          instructions: "Use the prompt words to ask and answer complete questions in one recording.",
          activity: {
            responseId: "sp2-recording",
            prompt: "Ask the questions for Card A, then answer the questions on Card B.",
            maxDurationSeconds: 120,
            cards: [
              { id: "sp2-card-a", title: "Card A · Ask about the sports club", prompts: ["Where?", "Which days?", "Start time?", "Cost?", "Bring?"] },
              { id: "sp2-card-b", title: "Card B · Answer about the art club", prompts: ["Place: Room 8", "Days: Tuesday and Thursday", "Time: 4:15", "Cost: £3", "Bring: an old shirt"] },
            ],
          },
        },
        {
          id: "speaking-part-3",
          partNumber: 3,
          kind: "speaking_picture_story",
          title: "Tell the story",
          instructions: "Look at the five pictures. Record a story with a beginning, middle, and ending.",
          activity: {
            responseId: "sp3-recording",
            prompt: "Tell the story in your own words. Try to connect the pictures with words such as first, then, after that, and finally.",
            maxDurationSeconds: 150,
            frames: [
              { id: "sp3-f1", src: "/pilots/games-listen-choose/hobbies/q1-drawing.webp", alt: "A child making a picture" },
              { id: "sp3-f2", src: "/pilots/games-listen-choose/hobbies/q2-ethan-riding-bike.webp", alt: "A child travelling by bicycle" },
              { id: "sp3-f3", src: "/pilots/games-listen-choose/hobbies/q3-leo-taking-photos.webp", alt: "A child taking photographs" },
              { id: "sp3-f4", src: "/pilots/games-listen-choose/hobbies/q4-zara-singing.webp", alt: "A child singing at a show" },
              { id: "sp3-f5", src: "/pilots/games-listen-choose/hobbies/q5-mia-zara-recording-art-project.webp", alt: "Friends recording their art project" },
            ],
          },
        },
      ],
    },
  ],
};
