"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { BookOpen, Check, Copy, Plus, Save, Trash2 } from "lucide-react";
import styles from "@/components/teacher/activity-builder/reading/ReadingSuite.module.css";
import { CLOZE_GAP_FOCUSES } from "@/lib/activity-builder/reading/cloze-choice";
import {
  clozeOpenValidationMessages,
  createClozeOpenDraft,
  isOpenClozeAnswerCorrect,
  type ClozeOpenDocument,
  type ClozeOpenGap,
  type ClozeOpenSegment,
} from "@/lib/activity-builder/reading/cloze-open";

const STORAGE_KEY = "wke-admin-reading-cloze-open-drafts:v1";
const inputClass = "mt-1 w-full rounded-lg border border-stone-300 bg-white px-3 py-2 text-sm text-stone-900 focus:border-sky-500 focus:outline-none focus:ring-2 focus:ring-sky-200";
const FOCUS_LABELS: Record<ClozeOpenGap["focus"], string> = { vocabulary: "Vocabulary", grammar: "Grammar", connector: "Connector", reference: "Reference word" };

function readDrafts(): ClozeOpenDocument[] { try { const value = JSON.parse(window.localStorage.getItem(STORAGE_KEY) ?? "[]"); return Array.isArray(value) ? value : []; } catch { return []; } }
function writeDrafts(drafts: ClozeOpenDocument[]) { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(drafts)); }

export function ClozeOpenWorkspace() {
  const [drafts, setDrafts] = useState<ClozeOpenDocument[]>([]);
  const [document, setDocument] = useState<ClozeOpenDocument | null>(null);
  const [notice, setNotice] = useState<string | null>(null);

  useEffect(() => { const timer = window.setTimeout(() => { const stored = readDrafts(); setDrafts(stored); setDocument(stored[0] ?? createClozeOpenDraft()); }, 0); return () => window.clearTimeout(timer); }, []);
  const errors = useMemo(() => document ? clozeOpenValidationMessages(document) : [], [document]);
  if (!document) return <div className="p-8 text-sm text-stone-500">Opening Reading Builder…</div>;

  const patch = (next: ClozeOpenDocument) => setDocument(next);
  const patchSegment = (segmentId: string, nextSegment: ClozeOpenSegment) => patch({ ...document, content: { ...document.content, segments: document.content.segments.map((segment) => segment.id === segmentId ? nextSegment : segment) } });
  const gaps = document.content.segments.filter((segment): segment is ClozeOpenGap => segment.type === "gap");
  const gapNumbers = new Map(gaps.map((gap, index) => [gap.id, index + 1]));
  const save = () => { const next = [document, ...drafts.filter((draft) => draft.id !== document.id)]; writeDrafts(next); setDrafts(next); setNotice(errors.length ? "Draft saved. Fix the validation items before review." : "Draft saved and ready for admin review."); };
  const duplicate = () => { const clone = structuredClone(document); clone.id = crypto.randomUUID(); clone.title = `${document.title} (copy)`; clone.content.segments = clone.content.segments.map((segment) => ({ ...segment, id: crypto.randomUUID() })); setDocument(clone); setNotice("Copy created. Save it when you are ready."); };
  const removeDraft = () => { const next = drafts.filter((draft) => draft.id !== document.id); writeDrafts(next); setDrafts(next); setDocument(next[0] ?? createClozeOpenDraft()); setNotice("Draft deleted."); };
  const addGap = () => { if (gaps.length >= 5) return; const finalIndex = Math.max(0, document.content.segments.length - 1); const newSegments = [...document.content.segments]; newSegments.splice(finalIndex, 0, { type: "text", id: crypto.randomUUID(), text: " Add more passage text " }, { type: "gap", id: crypto.randomUUID(), correctAnswers: ["answer"], hint: "Add a helpful meaning clue.", focus: "vocabulary" }); patch({ ...document, content: { ...document.content, segments: newSegments } }); };

  return <div className={`${styles.workspace} min-h-0 flex-1 overflow-y-auto bg-stone-50`}>
    <header className="sticky top-0 z-20 border-b border-stone-200 bg-white/95 px-4 py-3 backdrop-blur"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3"><div><Link href="/teacher/activity-builder" className="text-xs font-semibold text-sky-700 hover:underline">← Activity Builder</Link><h1 className="mt-1 text-xl font-bold text-stone-900">Open Cloze</h1><p className="text-xs font-medium text-amber-800">Admin development only · not publishable or assignable</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => { setDocument(createClozeOpenDraft()); setNotice(null); }} className="inline-flex items-center gap-1 rounded-lg border border-stone-300 bg-white px-3 py-2 text-xs font-semibold"><Plus className="h-4 w-4" />New</button><button type="button" onClick={duplicate} className="inline-flex items-center gap-1 rounded-lg border border-stone-300 bg-white px-3 py-2 text-xs font-semibold"><Copy className="h-4 w-4" />Duplicate</button><button type="button" onClick={removeDraft} className="inline-flex items-center gap-1 rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-800"><Trash2 className="h-4 w-4" />Delete</button><button type="button" onClick={save} className="inline-flex items-center gap-1 rounded-lg bg-sky-700 px-4 py-2 text-xs font-bold text-white"><Save className="h-4 w-4" />Save draft</button></div></div></header>
    <div className="mx-auto grid max-w-7xl gap-5 p-4 xl:grid-cols-[minmax(0,1fr)_minmax(28rem,0.9fr)]"><div className="space-y-4">
      {notice ? <p className="rounded-lg border border-sky-200 bg-sky-50 px-3 py-2 text-sm font-semibold text-sky-900">{notice}</p> : null}
      <section className="grid gap-3 rounded-xl border border-stone-200 bg-white p-4 sm:grid-cols-2"><label className="block text-sm font-semibold text-stone-800 sm:col-span-2">Activity title<input className={inputClass} value={document.title} onChange={(event) => patch({ ...document, title: event.target.value })} /></label><label className="block text-sm font-semibold text-stone-800 sm:col-span-2">Student instructions<input className={inputClass} value={document.instructions} onChange={(event) => patch({ ...document, instructions: event.target.value })} /></label><label className="block text-sm font-semibold text-stone-800 sm:col-span-2">Learning objective<input className={inputClass} value={document.learningObjective} onChange={(event) => patch({ ...document, learningObjective: event.target.value })} /></label><label className="block text-sm font-semibold text-stone-800">CEFR level<select className={inputClass} value={document.cefrLevel} onChange={(event) => patch({ ...document, cefrLevel: event.target.value as ClozeOpenDocument["cefrLevel"] })}><option value="pre_a1">Pre-A1</option><option value="a1">A1</option><option value="a2">A2</option></select></label><label className="block text-sm font-semibold text-stone-800">Estimated minutes<input className={inputClass} type="number" min={1} max={20} value={document.estimatedMinutes} onChange={(event) => patch({ ...document, estimatedMinutes: Number(event.target.value) })} /></label><label className="flex items-center gap-2 text-sm font-semibold text-stone-800"><input type="checkbox" checked={document.content.caseSensitive} onChange={(event) => patch({ ...document, content: { ...document.content, caseSensitive: event.target.checked } })} />Case-sensitive answers</label><label className="flex items-center gap-2 text-sm font-semibold text-stone-800"><input type="checkbox" checked={document.content.punctuationSensitive} onChange={(event) => patch({ ...document, content: { ...document.content, punctuationSensitive: event.target.checked } })} />Punctuation-sensitive answers</label></section>
      <section className="space-y-3 rounded-xl border border-stone-200 bg-white p-4"><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold text-stone-900">Passage builder</h2><p className="text-xs text-stone-500">Use 3–5 typed gaps. Add accepted alternatives when more than one answer is valid.</p></div><button type="button" disabled={gaps.length >= 5} onClick={addGap} className="rounded-lg border border-stone-300 px-3 py-2 text-xs font-semibold disabled:opacity-40">Add gap</button></div><label className="block text-sm font-semibold text-stone-800">Passage title<input className={inputClass} value={document.content.passageTitle ?? ""} onChange={(event) => patch({ ...document, content: { ...document.content, passageTitle: event.target.value } })} /></label><div className="space-y-3">{document.content.segments.map((segment) => segment.type === "text" ? <label key={segment.id} className="block rounded-lg border border-stone-200 bg-stone-50 p-3 text-xs font-semibold text-stone-700">Passage text<textarea className={inputClass} rows={2} value={segment.text} onChange={(event) => patchSegment(segment.id, { ...segment, text: event.target.value })} /></label> : <div key={segment.id} className="space-y-3 rounded-xl border-2 border-orange-200 bg-orange-50/60 p-3"><div className="flex items-center justify-between"><h3 className="text-sm font-bold text-orange-950">Gap {gapNumbers.get(segment.id)}</h3><button type="button" disabled={gaps.length <= 3} onClick={() => patch({ ...document, content: { ...document.content, segments: document.content.segments.filter((item) => item.id !== segment.id) } })} className="rounded p-2 text-rose-700 disabled:opacity-30" aria-label={`Remove gap ${gapNumbers.get(segment.id)}`}><Trash2 className="h-4 w-4" /></button></div><label className="block text-xs font-semibold text-stone-700">Accepted answers (one per line)<textarea className={inputClass} rows={3} value={segment.correctAnswers.join("\n")} onChange={(event) => patchSegment(segment.id, { ...segment, correctAnswers: event.target.value.split("\n") })} /></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-xs font-semibold text-stone-700">Hint<input className={inputClass} value={segment.hint ?? ""} onChange={(event) => patchSegment(segment.id, { ...segment, hint: event.target.value })} /></label><label className="block text-xs font-semibold text-stone-700">Focus<select className={inputClass} value={segment.focus} onChange={(event) => patchSegment(segment.id, { ...segment, focus: event.target.value as ClozeOpenGap["focus"] })}>{CLOZE_GAP_FOCUSES.map((focus) => <option key={focus} value={focus}>{FOCUS_LABELS[focus]}</option>)}</select></label></div></div>)}</div></section>
      <section className={`rounded-xl border p-4 ${errors.length ? "border-amber-300 bg-amber-50" : "border-emerald-300 bg-emerald-50"}`}><h2 className="flex items-center gap-2 text-sm font-bold text-stone-900">{errors.length ? "Before admin review" : <><Check className="h-4 w-4" />Ready for admin review</>}</h2>{errors.length ? <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-amber-950">{errors.map((error) => <li key={error}>{error}</li>)}</ul> : <p className="mt-1 text-sm text-emerald-900">All typed gaps have valid accepted answers.</p>}</section>
    </div><aside className="xl:sticky xl:top-24 xl:self-start"><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-stone-500"><BookOpen className="h-4 w-4" />Primary student preview</div><ClozeOpenPreview key={document.id} document={document} /></aside></div>
  </div>;
}

function ClozeOpenPreview({ document }: { document: ClozeOpenDocument }) {
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [attempts, setAttempts] = useState(0);
  const [revealed, setRevealed] = useState(false);
  const gaps = document.content.segments.filter((segment): segment is ClozeOpenGap => segment.type === "gap");
  const correct = gaps.filter((gap) => isOpenClozeAnswerCorrect(answers[gap.id] ?? "", gap, document.content)).length;
  return <div className="overflow-hidden rounded-3xl border-4 border-[#4a2c2a] bg-[#fff9f0] shadow-xl"><div className="bg-[#e76f51] px-5 py-4 text-white"><p className="text-xs font-black uppercase tracking-wide opacity-80">Open cloze · {document.cefrLevel.replace("_", "-").toUpperCase()}</p><h2 className="mt-1 text-xl font-black">{document.title}</h2><p className="mt-1 text-sm font-bold text-orange-50">{document.instructions}</p></div><div className="space-y-4 p-5"><article className="rounded-2xl border-2 border-orange-100 bg-white p-5 shadow-sm"><h3 className="mb-3 text-lg font-black text-[#4a2c2a]">{document.content.passageTitle}</h3><div className="text-base font-semibold leading-10 text-slate-700">{document.content.segments.map((segment) => segment.type === "text" ? <span key={segment.id}>{segment.text}</span> : <span key={segment.id} className="mx-1 inline-flex flex-col align-middle"><input disabled={revealed} value={revealed ? segment.correctAnswers[0] : answers[segment.id] ?? ""} onChange={(event) => setAnswers((current) => ({ ...current, [segment.id]: event.target.value }))} aria-label="Type the missing word" className={`w-28 rounded-lg border-2 px-2 py-1 text-center text-sm font-black ${attempts && isOpenClozeAnswerCorrect(answers[segment.id] ?? "", segment, document.content) ? "border-emerald-500 bg-emerald-50" : attempts ? "border-amber-500 bg-amber-50" : "border-[#e76f51] bg-white"}`} />{attempts > 0 && document.content.showHintsAfterFirstAttempt && !isOpenClozeAnswerCorrect(answers[segment.id] ?? "", segment, document.content) && segment.hint ? <small className="max-w-36 text-[10px] font-bold leading-3 text-amber-800">{segment.hint}</small> : null}</span>)}</div></article>{attempts > 0 ? <p className="rounded-2xl bg-[#4a2c2a] px-4 py-3 text-center text-sm font-black text-white">{correct} of {gaps.length} correct. {correct < gaps.length && !revealed ? "Use the hints and try again." : "Nice reading!"}</p> : null}{!revealed ? <div className="grid grid-cols-2 gap-2"><button type="button" disabled={Object.values(answers).filter((answer) => answer.trim()).length < gaps.length} onClick={() => setAttempts((value) => value + 1)} className="rounded-2xl bg-[#4a2c2a] px-4 py-3 text-sm font-black text-white disabled:opacity-40">{attempts ? "Check again" : "Check my words"}</button><button type="button" disabled={attempts < 2} onClick={() => setRevealed(true)} className="rounded-2xl border-2 border-[#4a2c2a] bg-white px-4 py-3 text-sm font-black text-[#4a2c2a] disabled:opacity-30">Show passage</button></div> : <div className="rounded-2xl border-2 border-orange-100 bg-white p-4"><p className="text-xs font-black uppercase tracking-wide text-orange-700">Complete passage</p><p className="mt-2 text-sm font-semibold leading-7 text-slate-700">{document.content.segments.map((segment) => segment.type === "text" ? segment.text : segment.correctAnswers[0]).join("")}</p></div>}</div></div>;
}
