import type { PuppetScript } from "../types";

/** Simple present: I + like vs she/he + likes (breakfast food context). */
export const LIKE_LIKES_FOOD: PuppetScript = {
  id: "like_likes_food",
  title: "Like / Likes",
  puppetId: "default_host",
  ttsLang: "en-US",
  maxVisibleLines: 4,
  defaultCaptionLayout: {
    xPercent: 50,
    yPercent: 78,
    scale: 1,
    widthPercent: 88,
    role: "headline",
  },
  beats: [
    {
      kind: "line",
      text: "Hi!",
      puppetAnimation: "wave",
      wordStaggerMs: 100,
      captionLayout: { xPercent: 50, yPercent: 72, role: "headline" },
    },
    {
      kind: "line",
      text: "Today we learn like and likes with food.",
      puppetAnimation: "nod",
      wordStaggerMs: 120,
      captionLayout: { xPercent: 50, yPercent: 82, role: "headline", size: "md" },
    },
    {
      kind: "choice",
      prompt: "Tap a food you like!",
      foodIds: ["bread", "milk", "juice", "eggs", "apple", "banana"],
      storeAs: "food",
      puppetAnimation: "wave",
      captionLayout: { xPercent: 50, yPercent: 18, role: "subtitle", widthPercent: 92 },
    },
    {
      kind: "line",
      text: "like",
      persist: true,
      captionSlot: "left",
      wordStaggerMs: 80,
      captionLayout: {
        xPercent: 28,
        yPercent: 36,
        role: "label",
        scale: 1.05,
      },
    },
    {
      kind: "line",
      text: "likes",
      persist: true,
      captionSlot: "right",
      wordStaggerMs: 80,
      captionLayout: {
        xPercent: 72,
        yPercent: 36,
        role: "label",
        scale: 1.05,
      },
    },
    {
      kind: "line",
      text: "I like {{food}}.",
      wordStaggerMs: 130,
      captionSlot: "left",
      captionLayout: {
        xPercent: 28,
        yPercent: 62,
        role: "subtitle",
        size: "sm",
        widthPercent: 50,
        showPanel: true,
      },
    },
    {
      kind: "line",
      text: "She likes {{food}}.",
      puppetAnimation: "nod",
      wordStaggerMs: 130,
      captionSlot: "right",
      captionLayout: {
        xPercent: 72,
        yPercent: 62,
        role: "subtitle",
        size: "sm",
        widthPercent: 50,
        showPanel: true,
      },
    },
    {
      kind: "line",
      text: "He likes eggs.",
      wordStaggerMs: 120,
      captionSlot: "main",
      captionLayout: {
        xPercent: 50,
        yPercent: 86,
        role: "subtitle",
        size: "sm",
        widthPercent: 55,
      },
    },
    {
      kind: "quiz_true_false",
      statement: "We say: I likes {{food}}.",
      correct: false,
    },
  ],
};
