/**
 * Secondary wordItemId → platform/primary lexicon id (pv_*) mapping.
 * Generated by `npm run generate:secondary-primary-lexicon-map` — do not hand-edit bulk rows.
 */

export type SecondaryLexiconMapConfidence = "exact";

export type SecondaryLexiconMapEntryStatus =
  | "mapped"
  | "pos_conflict"
  | "secondary_only"
  | "ambiguous_same_pos";

export type SecondaryLexiconMappedEntry = {
  wordItemId: string;
  lexiconId: string;
  status: "mapped";
  confidence: SecondaryLexiconMapConfidence;
  lemma: string;
  rawPos: string;
  matchPos: string | null;
  topicId: string;
  setId: string;
};

export type SecondaryLexiconReviewEntry = {
  wordItemId: string;
  status: Exclude<SecondaryLexiconMapEntryStatus, "mapped">;
  lemma: string;
  word: string;
  rawPos: string;
  matchPos: string | null;
  topicId: string;
  setId: string;
  candidateLexiconIds: string[];
  note?: string;
};

export type SecondaryToPrimaryLexiconMapDataset = {
  schemaVersion: 1;
  datasetVersion: string;
  title: string;
  secondaryPackId: string;
  secondaryPackVersion: string;
  primaryIndexPath: string;
  primaryEntryCount: number;
  method: "exact_lemma_pos_v1";
  generatedAt: string;
  counts: {
    mapped: number;
    pos_conflict: number;
    secondary_only: number;
    ambiguous_same_pos: number;
    total: number;
  };
  /** High-confidence auto-maps only. */
  mappings: SecondaryLexiconMappedEntry[];
  /** Needs human decision before writing a lexiconId. */
  reviewQueue: SecondaryLexiconReviewEntry[];
  /** No Primary lemma hit — promote as new dictionary candidates. */
  unmapped: SecondaryLexiconReviewEntry[];
};
