import "server-only";
import type { EnglishCraftAdjectiveQuestion, EnglishCraftCraftQuestion } from "@/lib/live-game/modes/english-craft/questions-v1";

/** Grade 5–6 adjectives — generated from Grade 56 adjectives 60 question bank.docx */
export const GRADE56_ADJECTIVES_MC_V1: EnglishCraftAdjectiveQuestion[] = [
  {
    id: "adj-001",
    prompt: "We went to an enormous science museum. The word enormous means:",
    options: ["small", "exciting", "very big", "colorful"],
    correctAnswer: "very big",
    targetWord: "enormous",
    spellHint: "very big",
  },
  {
    id: "adj-002",
    prompt: "Mia found a tiny insect on the leaf. The word tiny means:",
    options: ["very small", "dangerous", "noisy", "strange"],
    correctAnswer: "very small",
    targetWord: "tiny",
    spellHint: "very small",
  },
  {
    id: "adj-003",
    prompt: "The shopping center was crowded on Saturday afternoon. This means:",
    options: ["it was closed", "it was full of people", "it was very clean", "it had no shops"],
    correctAnswer: "it was full of people",
    targetWord: "crowded",
    spellHint: "it was full of people",
  },
  {
    id: "adj-004",
    prompt: "The streets were empty early in the morning. This means:",
    options: ["there were very few people", "there were many cars", "the streets were dirty", "the streets were narrow"],
    correctAnswer: "there were very few people",
    targetWord: "empty",
    spellHint: "there were very few people",
  },
  {
    id: "adj-005",
    prompt: "We visited an ancient temple during our trip. The word ancient means:",
    options: ["very modern", "very old", "very tall", "very famous"],
    correctAnswer: "very old",
    targetWord: "ancient",
    spellHint: "very old",
  },
  {
    id: "adj-006",
    prompt: "Our school has a modern computer room. The word modern means:",
    options: ["old-fashioned", "new and up to date", "small and dark", "difficult to use"],
    correctAnswer: "new and up to date",
    targetWord: "modern",
    spellHint: "new and up to date",
  },
  {
    id: "adj-007",
    prompt: "The waiter was very polite and spoke kindly to us. The word polite means:",
    options: ["showing good manners", "speaking loudly", "feeling worried", "working slowly"],
    correctAnswer: "showing good manners",
    targetWord: "polite",
    spellHint: "showing good manners",
  },
  {
    id: "adj-008",
    prompt: "It was rude to interrupt the teacher while she was speaking. The word rude means:",
    options: ["helpful", "not polite", "cheerful", "careful"],
    correctAnswer: "not polite",
    targetWord: "rude",
    spellHint: "not polite",
  },
  {
    id: "adj-009",
    prompt: "Leo is generous because he often shares his snacks with others. The word generous means:",
    options: ["willing to give and share", "afraid of losing things", "unable to make friends", "interested in cooking"],
    correctAnswer: "willing to give and share",
    targetWord: "generous",
    spellHint: "willing to give and share",
  },
  {
    id: "adj-010",
    prompt: "Max was selfish and kept all the game pieces for himself. The word selfish means:",
    options: ["thinking mainly about yourself", "helping everyone", "feeling very tired", "working carefully"],
    correctAnswer: "thinking mainly about yourself",
    targetWord: "selfish",
    spellHint: "thinking mainly about yourself",
  },
  {
    id: "adj-011",
    prompt: "Our coach was patient and explained the activity three times. This means the coach:",
    options: ["became angry quickly", "waited calmly", "forgot the instructions", "spoke very quietly"],
    correctAnswer: "waited calmly",
    targetWord: "patient",
    spellHint: "waited calmly",
  },
  {
    id: "adj-012",
    prompt: "I felt nervous before giving my speech. This means I felt:",
    options: ["worried", "hungry", "proud", "bored"],
    correctAnswer: "worried",
    targetWord: "nervous",
    spellHint: "worried",
  },
  {
    id: "adj-013",
    prompt: "Ava felt proud after completing the difficult project. This means she was:",
    options: ["pleased with what she had done", "afraid of making a mistake", "angry with her classmates", "confused by the project"],
    correctAnswer: "pleased with what she had done",
    targetWord: "pleased with what she had done",
    spellHint: "pleased with what she had done",
  },
  {
    id: "adj-014",
    prompt: "We were disappointed when the football match was canceled. This means we felt:",
    options: ["pleased", "surprised and excited", "unhappy because something did not happen", "tired after playing"],
    correctAnswer: "unhappy because something did not happen",
    targetWord: "disappointed",
    spellHint: "unhappy because something did not happen",
  },
  {
    id: "adj-015",
    prompt: "Ben is very cheerful and usually has a smile on his face. The word cheerful means:",
    options: ["happy and positive", "quiet and shy", "serious and worried", "tired and weak"],
    correctAnswer: "happy and positive",
    targetWord: "cheerful",
    spellHint: "happy and positive",
  },
  {
    id: "adj-016",
    prompt: "The new student was shy and did not speak much. This means the student:",
    options: ["felt uncomfortable meeting people", "was angry with the class", "wanted to be the leader", "spoke too loudly"],
    correctAnswer: "felt uncomfortable meeting people",
    targetWord: "shy",
    spellHint: "felt uncomfortable meeting people",
  },
  {
    id: "adj-017",
    prompt: "The soup was delicious , so I asked for another bowl. The word delicious means:",
    options: ["very tasty", "too hot", "expensive", "unhealthy"],
    correctAnswer: "very tasty",
    targetWord: "delicious",
    spellHint: "very tasty",
  },
  {
    id: "adj-018",
    prompt: "The milk smelled awful , so we did not drink it. The word awful means:",
    options: ["very pleasant", "very bad", "fresh and cold", "sweet and tasty"],
    correctAnswer: "very bad",
    targetWord: "awful",
    spellHint: "very bad",
  },
  {
    id: "adj-019",
    prompt: "The path was very narrow , so only one person could walk along it. The word narrow means:",
    options: ["not wide", "very long", "difficult to find", "covered in water"],
    correctAnswer: "not wide",
    targetWord: "narrow",
    spellHint: "not wide",
  },
  {
    id: "adj-020",
    prompt: "The river is wide near the bridge. This means:",
    options: ["the river is deep", "the river has a large distance from one side to the other", "the river is very clean", "the river moves quickly"],
    correctAnswer: "the river has a large distance from one side to the other",
    targetWord: "wide",
    spellHint: "the river has a large distance from one side to the other",
  },
  {
    id: "adj-021",
    prompt: "The classroom was too noisy for us to hear the instructions. The word noisy means:",
    options: ["full of loud sounds", "completely empty", "very bright", "cold and uncomfortable"],
    correctAnswer: "full of loud sounds",
    targetWord: "noisy",
    spellHint: "full of loud sounds",
  },
  {
    id: "adj-022",
    prompt: "The library is usually quiet , so it is a good place to study. The word quiet means:",
    options: ["not making much noise", "full of interesting books", "difficult to enter", "crowded with students"],
    correctAnswer: "not making much noise",
    targetWord: "quiet",
    spellHint: "not making much noise",
  },
  {
    id: "adj-023",
    prompt: "This dictionary is very useful when I do my homework. The word useful means:",
    options: ["helpful for a purpose", "difficult to understand", "old and damaged", "expensive to buy"],
    correctAnswer: "helpful for a purpose",
    targetWord: "useful",
    spellHint: "helpful for a purpose",
  },
  {
    id: "adj-024",
    prompt: "It is dangerous to cross the road without looking. The word dangerous means:",
    options: ["likely to cause harm", "easy to do", "exciting and fun", "allowed by the rules"],
    correctAnswer: "likely to cause harm",
    targetWord: "dangerous",
    spellHint: "likely to cause harm",
  },
  {
    id: "adj-025",
    prompt: "The chair has a soft seat and supports my back. It is very ______.",
    options: ["crowded", "comfortable", "ancient", "nervous"],
    correctAnswer: "comfortable",
    targetWord: "comfortable",
    spellHint: "comfortable",
  },
  {
    id: "adj-026",
    prompt: "I have never seen a purple tree before. It looks very ______.",
    options: ["usual", "patient", "unusual", "polite"],
    correctAnswer: "unusual",
    targetWord: "unusual",
    spellHint: "unusual",
  },
  {
    id: "adj-027",
    prompt: "The instructions were easy to follow because they were very ______.",
    options: ["clear", "empty", "rude", "narrow"],
    correctAnswer: "clear",
    targetWord: "clear",
    spellHint: "clear",
  },
  {
    id: "adj-028",
    prompt: "We could not lift the box because it was too ______.",
    options: ["light", "heavy", "quiet", "friendly"],
    correctAnswer: "heavy",
    targetWord: "heavy",
    spellHint: "heavy",
  },
  {
    id: "adj-029",
    prompt: "The glass fell on the floor, but it did not break. It was surprisingly ______.",
    options: ["strong", "weak", "nervous", "delicious"],
    correctAnswer: "strong",
    targetWord: "surprisingly",
    spellHint: "strong",
  },
  {
    id: "adj-030",
    prompt: "The maths problem was ______, but I solved it after thinking carefully.",
    options: ["generous", "difficult", "crowded", "modern"],
    correctAnswer: "difficult",
    targetWord: "______",
    spellHint: "difficult",
  },
  {
    id: "adj-031",
    prompt: "After walking for five hours, we felt exhausted . The word exhausted means:",
    options: ["very tired", "very hungry", "very worried", "very cold"],
    correctAnswer: "very tired",
    targetWord: "exhausted",
    spellHint: "very tired",
  },
  {
    id: "adj-032",
    prompt: "The lake was freezing , so nobody wanted to swim in it. The word freezing means:",
    options: ["extremely cold", "slightly dirty", "very deep", "full of fish"],
    correctAnswer: "extremely cold",
    targetWord: "freezing",
    spellHint: "extremely cold",
  },
  {
    id: "adj-033",
    prompt: "Be careful with the soup because it is boiling . The word boiling means:",
    options: ["extremely hot", "ready to eat", "very salty", "almost empty"],
    correctAnswer: "extremely hot",
    targetWord: "boiling",
    spellHint: "extremely hot",
  },
  {
    id: "adj-034",
    prompt: "Our clothes were wet after we walked home in the rain. The word wet means:",
    options: ["covered with water", "covered with dirt", "too small", "very warm"],
    correctAnswer: "covered with water",
    targetWord: "wet",
    spellHint: "covered with water",
  },
  {
    id: "adj-035",
    prompt: "The ground was dry because it had not rained for weeks. The word dry means:",
    options: ["not wet", "very soft", "full of plants", "difficult to cross"],
    correctAnswer: "not wet",
    targetWord: "dry",
    spellHint: "not wet",
  },
  {
    id: "adj-036",
    prompt: "The surface of the glass table was smooth . The word smooth means:",
    options: ["even and not rough", "broken into pieces", "covered with paint", "heavy to carry"],
    correctAnswer: "even and not rough",
    targetWord: "smooth",
    spellHint: "even and not rough",
  },
  {
    id: "adj-037",
    prompt: "The old wall felt rough when I touched it. The word rough means:",
    options: ["not smooth", "very clean", "soft and warm", "easy to move"],
    correctAnswer: "not smooth",
    targetWord: "rough",
    spellHint: "not smooth",
  },
  {
    id: "adj-038",
    prompt: "The classroom was bright because sunlight came through the large windows. The word bright means:",
    options: ["full of light", "full of students", "difficult to find", "painted white"],
    correctAnswer: "full of light",
    targetWord: "bright",
    spellHint: "full of light",
  },
  {
    id: "adj-039",
    prompt: "The cave was very dark , so we used a flashlight. The word dark means:",
    options: ["having little or no light", "being very cold", "being difficult to enter", "having many tunnels"],
    correctAnswer: "having little or no light",
    targetWord: "dark",
    spellHint: "having little or no light",
  },
  {
    id: "adj-040",
    prompt: "We bought fruit from a local market near our hotel. The word local means:",
    options: ["from the nearby area", "from another country", "open all night", "very expensive"],
    correctAnswer: "from the nearby area",
    targetWord: "local",
    spellHint: "from the nearby area",
  },
  {
    id: "adj-041",
    prompt: "Our class welcomed a foreign student from another country. The word foreign means:",
    options: ["from a different country", "from the same town", "new to the school", "unable to speak"],
    correctAnswer: "from a different country",
    targetWord: "foreign",
    spellHint: "from a different country",
  },
  {
    id: "adj-042",
    prompt: "The bicycle was too expensive , so I did not have enough money to buy it. The word expensive means:",
    options: ["costing a lot of money", "difficult to ride", "made a long time ago", "too large to use"],
    correctAnswer: "costing a lot of money",
    targetWord: "expensive",
    spellHint: "costing a lot of money",
  },
  {
    id: "adj-043",
    prompt: "These notebooks were very cheap , so I bought three of them. The word cheap means:",
    options: ["not costing much money", "difficult to find", "made from paper", "available in many colors"],
    correctAnswer: "not costing much money",
    targetWord: "cheap",
    spellHint: "not costing much money",
  },
  {
    id: "adj-044",
    prompt: "Fruit, vegetables, and exercise can help us stay healthy . The word healthy means:",
    options: ["well and strong", "tired and sleepy", "hungry and thirsty", "quiet and calm"],
    correctAnswer: "well and strong",
    targetWord: "healthy",
    spellHint: "well and strong",
  },
  {
    id: "adj-045",
    prompt: "Theo was too lazy to clean his room, so his clothes stayed on the floor. The word lazy means:",
    options: ["not willing to work", "unable to find something", "excited about a task", "worried about a problem"],
    correctAnswer: "not willing to work",
    targetWord: "lazy",
    spellHint: "not willing to work",
  },
  {
    id: "adj-046",
    prompt: "The brave firefighter entered the building to help the family. The word brave means:",
    options: ["willing to face danger", "unable to understand danger", "afraid to help people", "angry about a problem"],
    correctAnswer: "willing to face danger",
    targetWord: "brave",
    spellHint: "willing to face danger",
  },
  {
    id: "adj-047",
    prompt: "Maya was honest and told the teacher that she had broken the ruler. The word honest means:",
    options: ["telling the truth", "making a mistake", "speaking quietly", "feeling sorry"],
    correctAnswer: "telling the truth",
    targetWord: "honest",
    spellHint: "telling the truth",
  },
  {
    id: "adj-048",
    prompt: "Please be careful when you carry the glasses. The word careful means:",
    options: ["trying to avoid mistakes or damage", "trying to finish very quickly", "asking someone else for help", "feeling unable to continue"],
    correctAnswer: "trying to avoid mistakes or damage",
    targetWord: "careful",
    spellHint: "trying to avoid mistakes or damage",
  },
  {
    id: "adj-049",
    prompt: "It was careless to leave the door open when we went outside. The word careless means:",
    options: ["not paying enough attention", "trying to be helpful", "feeling afraid of something", "working very slowly"],
    correctAnswer: "not paying enough attention",
    targetWord: "careless",
    spellHint: "not paying enough attention",
  },
  {
    id: "adj-050",
    prompt: "The curious child asked many questions about the robot. The word curious means:",
    options: ["wanting to learn more", "unable to remember", "ready to leave", "unhappy with the answer"],
    correctAnswer: "wanting to learn more",
    targetWord: "curious",
    spellHint: "wanting to learn more",
  },
  {
    id: "adj-051",
    prompt: "The singer became famous after millions of people watched her video. The word famous means:",
    options: ["known by many people", "liked by one person", "able to sing loudly", "interested in music"],
    correctAnswer: "known by many people",
    targetWord: "famous",
    spellHint: "known by many people",
  },
  {
    id: "adj-052",
    prompt: "We were lucky because we found the missing key before the shop closed. The word lucky means:",
    options: ["having something good happen by chance", "working carefully for a long time", "knowing exactly what to do", "feeling unhappy about a result"],
    correctAnswer: "having something good happen by chance",
    targetWord: "lucky",
    spellHint: "having something good happen by chance",
  },
  {
    id: "adj-053",
    prompt: "Sam was unlucky when his bicycle got a flat tire during the race. The word unlucky means:",
    options: ["having something bad happen by chance", "being unable to ride quickly", "not preparing for an activity", "losing something important"],
    correctAnswer: "having something bad happen by chance",
    targetWord: "unlucky",
    spellHint: "having something bad happen by chance",
  },
  {
    id: "adj-054",
    prompt: "I was surprised when my classmates gave me a birthday cake. The word surprised means:",
    options: ["feeling something unexpected happened", "feeling angry about a mistake", "feeling tired after working", "feeling unsure about an answer"],
    correctAnswer: "feeling something unexpected happened",
    targetWord: "surprised",
    spellHint: "feeling something unexpected happened",
  },
  {
    id: "adj-055",
    prompt: "The children were frightened when they heard a strange sound outside. The word frightened means:",
    options: ["afraid", "interested", "pleased", "confused"],
    correctAnswer: "afraid",
    targetWord: "frightened",
    spellHint: "afraid",
  },
  {
    id: "adj-056",
    prompt: "We became bored because the bus journey lasted six hours. The word bored means:",
    options: ["not interested and wanting something to do", "worried about arriving late", "excited about the journey", "unable to find a seat"],
    correctAnswer: "not interested and wanting something to do",
    targetWord: "bored",
    spellHint: "not interested and wanting something to do",
  },
  {
    id: "adj-057",
    prompt: "The students were excited about visiting the space center. The word excited means:",
    options: ["very happy and interested about something coming", "too tired to join an activity", "afraid that something will go wrong", "unhappy about a change"],
    correctAnswer: "very happy and interested about something coming",
    targetWord: "excited",
    spellHint: "very happy and interested about something coming",
  },
  {
    id: "adj-058",
    prompt: "The restaurant was busy , and every table had customers. The word busy means:",
    options: ["having a lot of activity or work", "having very little food", "being closed for the day", "being difficult to reach"],
    correctAnswer: "having a lot of activity or work",
    targetWord: "busy",
    spellHint: "having a lot of activity or work",
  },
  {
    id: "adj-059",
    prompt: "The game has simple rules, so everyone learned how to play quickly. The word simple means:",
    options: ["easy to understand", "difficult to remember", "unfair to some players", "slow and uninteresting"],
    correctAnswer: "easy to understand",
    targetWord: "simple",
    spellHint: "easy to understand",
  },
  {
    id: "adj-060",
    prompt: "This necklace is special because it belonged to my grandmother. The word special means:",
    options: ["important or different in a meaningful way", "easy to replace", "expensive to repair", "difficult to wear"],
    correctAnswer: "important or different in a meaningful way",
    targetWord: "special",
    spellHint: "important or different in a meaningful way",
  },
];

export const GRADE56_ADJECTIVES_CRAFT_V1: EnglishCraftCraftQuestion = {
  id: "adj-craft-bridge",
  prompt: "Put the sentence in order to build the bridge:",
  wordBank: ["The", "enormous", "museum", "was", "very", "interesting"],
  correctOrder: ["The", "enormous", "museum", "was", "very", "interesting"],
  slotCount: 6,
};
